name: dont_touch_red
description: "Don't Touch Red - Tap only green tiles!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0
  audioplayers: ^6.1.0
  google_fonts: ^6.2.1
  share_plus: ^10.1.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
